# -*- coding: utf-8 -*-
"""Clientes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16RKpQorKBUU9zrytqM88ZKBYGCcuRWeX

https://github.com/MiguelUTEC26/datawarehouse-seguros.git
"""

import pandas as pd

"""BLOQUE 1: CARGA DEL DATASET"""

#Ruta del dataset almacenada en GitHub
url = "https://raw.githubusercontent.com/MiguelUTEC26/datawarehouse-seguros/refs/heads/main/data/clientes.csv"

#Lectura del archivo
df = pd.read_csv(url)
print ("Dataset cargado correctamente")

display(df.head())

"""BLOQUE 2: Exploración del DATASET"""

print("Primeras filas del dataset")
display(df.head())

print("Dimensiones del dataset (filas, columnas)")
print(df.shape)

print ("Columnas del dataset")
print (df.columns)

print ("Tipos de datos")
print (df.dtypes)

print("Valores nulos por columna")
print(df.isnull().sum())

print ("Registros duplicados")
print (df.duplicated().sum())

"""BLOQUE 3: Limpieza de datos"""

#Elimina espacios al inicio y al final en columnas de texto
for col in df.select_dtypes(include="object").columns:df[col]=df[col].str.strip()

#Normalizar nombre
df["nombre"]=df["nombre"].str.title()

#Normalizar email
df["email"]=df["email"].str.lower()

#Normalizar gennero
df["genero"]=df["genero"].str.upper()

#Convertir fecha de nacimiento a formato fecha
df["fecha_nacimiento"]=df["fecha_nacimiento"]=pd.to_datetime(df['fecha_nacimiento'],errors="coerce")

#Normalizar ciudad
df["ciudad"]=df['ciudad'].str.title()

#Limpieza de segmento
df['segmento']=df['segmento'].astype(str)
df['segmento']=df['segmento'].str.strip()
df['segmento']=df['segmento'].str.upper()

for col in df.columns: print (col)

"""BLOQUE 4: Validación de datos"""

#